version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000" # Flask (Gunicorn) 외부 연셜
    environment:
      - APP_ENV=prod
      - FLASK_ENV=production # 운영 모드
      - OPENAI_API_KEY: ${OPENAI_API_KEY}
      - NAVER_CLOVA_API_KEY: ${NAVER_CLOVA_API_KEY}
      - NAVER_CLOVA_API_URL: ${NAVER_CLOVA_API_URL}
    depends_on:
      - qdrant # Qdrant 먼저 시작
    restart: always # 서버 재시작 시 자동 복구
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health-check"]
      interval: 10s
      timeout: 3s
      retries: 5

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333" # Qdrant 기본 포트
    volumes:
      - qdrant_storage:/qdrant/storage # 데이터 영속화
    restart: always # 자동 재시작
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000

volumes:
  qdrant_storage: # Qdrant 데이터 보존
