on:
   push:
     branches: [main, develop, deploy_test]
   pull_request:
     branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and start containers
      run: docker compose up -d --build
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        AZURE_EMBEDDING_API_KEY: ${{ secrets.AZURE_EMBEDDING_API_KEY }}
        AZURE_EMBEDDING_OPENAI_ENDPOINT: ${{ secrets.AZURE_EMBEDDING_OPENAI_ENDPOINT }}
        AZURE_PROMPT_API_KEY: ${{ secrets.AZURE_PROMPT_API_KEY }}
        AZURE_PROMPT_OPENAI_ENDPOINT: ${{ secrets.AZURE_PROMPT_OPENAI_ENDPOINT }}


    # ✅ Flask health check (실패할 수 있음)
    - name: Check Flask health
      run: |
        echo "Waiting for Flask to become ready..."
        for i in {1..10}; do
          if curl --fail http://localhost:5000/health-check; then
            echo "Flask is healthy"
            break
          fi
          echo "Flask not ready yet... retrying in 3s"
          sleep 3
        done

    - name: Show Flask logs (for debugging)
      if: always()
      run: docker compose logs flask-app

    - name: Tear down containers
      if: always()
      run: docker compose down